name: github pages

on:
  push:
    branches:
      - src

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup esbuild
        run: |
          wget -q https://registry.npmjs.org/esbuild-linux-64/-/esbuild-linux-64-0.8.33.tgz
          tar xf esbuild-linux-64-0.8.33.tgz
          mv package/bin/esbuild bin
          rm -fr package
      - run: ./bin/esbuild --bundle src/index.ts --outdir=public --minify
      - run: cp index.html public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public